### ISSUE TITLE
Add position: sticky to header element

### ISSUE THREAD

**Issue by gelafin** [gelafin/flexbox-stylish-layout#3]
sucker for sticky nav

**Comment by gelafin** [comment]
hm, applying 
```CSS
body > header:first-of-type {
    position: sticky;
    top: 0;
}
```
had no effect. Chrome dev tools shows that it is applied to the correct element but the element acts like a static element when scrolling
