### ISSUE TITLE
can't add margin to flex items?

### ISSUE THREAD

**Issue by gelafin** [gelafin/flexbox-stylish-layout#4]
This is crossed out as an "invalid property" by Chrome:
```CSS
.central-column > * {
    margin-bottom: 20 px;
}
```
